[package]
name = "proxy"
version = "0.1.0"
authors = ["Alexandre Kirszenberg <alexandre.kirszenberg@epita.fr>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
futures = "0.3.12"
async-std = "1.9.0"
socksv5 = { path = "../.." }
log = "0.4.13"
env_logger = "0.8.2"
